print(" Arredondador do marcio")
n1 = float(input("g "))
media = round(n1)
n2 = float(input("g "))
media2 = round(n2)
n3 = float(input("g "))
media3 = round(n3)
n4 = float(input("g "))
media4 = round(n4)
n5 = float(input("g "))
media5 = round(n5)
n6 = float(input("g "))
media6 = round(n6)
n7 = float(input("g "))
media7 = round(n7)
print(" O resultado do arredondamento é", media,",", media2, ",", media3, ",", media4, ",", media5, ",", media6, "e", media7)
